### ISSUE TITLE
Error message null for ModelServiceInternalServerErrorException

### ISSUE THREAD

**Issue by CharlotteHermans** [sdl/dxa-web-application-java#115]
In the log file of my DXA application I noticed the exception message is null for ModelServiceInternalServerErrorException:

2018-10-11 14:19:05,024 [https-jsse-nio2-8443-exec-6] INFO c.s.d.t.m.ModelServiceClient     - Got response with a status code 500
2018-10-11 14:19:05,025 [https-jsse-nio2-8443-exec-6] WARN     c.s.d.t.m.ModelServiceClient - Internal server error requesting     '/PageModel/{uriType}/{localizationId}/{pageUrl}?includes={pageInclusion}&raw=true'     with params '[tcm, 15, /nl/navigation.json, INCLUDE]'
2018-10-11 14:19:05,032 [https-jsse-nio2-8443-exec-6] ERROR     c.s.w.c.controller.BaseController - Exception while processing request for:     https://www.svb.nl/WEB-INF/Views/svbnl-basis/Page/AlgemenePagina.jsp     com.sdl.webapp.common.api.navigation.NavigationProviderException: Exception     while loading navigation model at     com.sdl.webapp.tridion.navigation.StaticNavigationProvider.getNavigationModel(StaticNavigationProvider.java:131)     at     ....
Caused by:     com.sdl.webapp.common.api.content.ContentProviderException: Cannot load     page from model service at     com.sdl.dxa.tridion.modelservice.DefaultModelService._loadPage(DefaultModelService.java:64)     at     com.sdl.dxa.tridion.modelservice.DefaultModelService.loadPageContent(DefaultModelService.java:51)     at     com.sdl.webapp.tridion.navigation.StaticNavigationProvider.getPageContent(StaticNavigationProvider.java:176)     at com.sdl.webapp.tridion.navigation.StaticNavigationProvider.getNavigationModel(StaticNavigationProvider.java:129)     ... 159 common frames omitted 
Caused by:     com.sdl.dxa.tridion.modelservice.exceptions.ModelServiceInternalServerErrorException:     **null** at com.sdl.dxa.tridion.modelservice.ModelServiceClient._makeRequest(ModelServiceClient.java:89)     at     com.sdl.dxa.tridion.modelservice.ModelServiceClient.getForType(ModelServiceClient.java:57)     at     com.sdl.dxa.tridion.modelservice.ModelServiceClient$$FastClassBySpringCGLIB$$83049939.invoke()     at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)     at     org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)     at     org.springframework.cache.jcache.interceptor.JCacheInterceptor$1.invoke(JCacheInterceptor.java:52)     at     org.springframework.cache.jcache.interceptor.JCacheAspectSupport.invokeOperation(JCacheAspectSupport.java:161)     at     org.springframework.cache.jcache.interceptor.JCacheAspectSupport$CacheOperationInvokerAdapter.invoke(JCacheAspectSupport.java:175)     at     org.springframework.cache.jcache.interceptor.CacheResultInterceptor.invoke(CacheResultInterceptor.java:62)     at org.springframework.cache.jcache.interceptor.JCacheAspectSupport.execute(JCacheAspectSupport.java:131)     at     org.springframework.cache.jcache.interceptor.JCacheAspectSupport.execute(JCacheAspectSupport.java:102)     at org.springframework.cache.jcache.interceptor.JCacheInterceptor.invoke(JCacheInterceptor.java:61)     at     org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)     at     org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)     at     com.sdl.dxa.tridion.modelservice.ModelServiceClient$$EnhancerBySpringCGLIB$$d01dae37.getForType()     at     com.sdl.dxa.tridion.modelservice.DefaultModelService._loadPage(DefaultModelService.java:56)     ... 162 common frames omitted

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-12808

**Comment by rpannekoek** [comment]
Fixed in DXA 2.2
