### ISSUE TITLE
DXA version 2.2.18. Upgrade to Jackson 2.13.4 results in the exception: Cannot get a source converter for class java.util.LinkedHashMap

### ISSUE THREAD

**Issue by CodingAnoop** [sdl/dxa-web-application-java#178]
Using DXA version 2.2.18. When I tried to upgrade to Jackson 2.13.4, getting the following exception. Jackson 2.10.0 works fine. Does DXA not support Jackson 2.13.4?:

[http-nio-8080-exec-10] WARN c.s.d.t.m.c.GenericSemanticModelDataConverter - Cannot get a source converter for class java.util.LinkedHashMap [http-nio-8080-exec-10] ERROR c.s.w.c.i.mapping.SemanticMapperImpl - Exception while getting field data.... com.sdl.webapp.tridion.fields.exceptions.UnsupportedTargetTypeException: Unsupported target class: java.util.LinkedHashMap at com.sdl.dxa.tridion.mapping.converter.GenericSemanticModelDataConverter.getSourceConverter(GenericSemanticModelDataConverter.java:82) at com.sdl.dxa.tridion.mapping.converter.GenericSemanticModelDataConverter.convert(GenericSemanticModelDataConverter.java:72) at com.sdl.dxa.tridion.mapping.impl.DefaultSemanticFieldDataProvider.getFieldData(DefaultSemanticFieldDataProvider.java:138)

**Comment by dxasupport** [comment]
DXA version 2.2.28 has already been updated to using Jackson 2.13.4 and also the latest version of Spring MVC.
