### ISSUE TITLE
DXA version 2.2.18. Upgrade of SpringBoot to v2.5.12 resulted in the exception "Failed to retrieve localization for request url"

### ISSUE THREAD

**Issue by CodingAnoop** [sdl/dxa-web-application-java#179]
Using DXA version 2.2.18. Current version of Spring Boot: 2.1.17.RELEASE. When I tried to upgrade to 2.5.12, getting the following exception. Does DXA not support Spring Boot version 2.5.12?:

Failed to retrieve localization for request url....
at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at com.sdl.webapp.common.impl.WebRequestContextImpl.localization(WebRequestContextImpl.java:256)

**Comment by dxasupport** [comment]
The DXA is a Spring MVC application. The use of Spring Boot requires custom adaptations. I would advise using the latest version available (2.2.28), which is updated to using the latest version of the Spring MVC and take it from there.
